# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1260, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1260, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1260, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.502975, y1:0, x2:0.473, y2:1, stop:0 rgba(2, 11, 16, 255), stop:1 rgba(4, 26, 37, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1174, 500, 41, 31))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;")
        self.label_18.setObjectName("label_18")
        self.count = QtWidgets.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(980, 485, 265, 61))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.count.setFont(font)
        self.count.setStyleSheet("color: white;\n"
"background-color: #5e5e5e;\n"
"border: 1px solid white;\n"
"padding-left: 10%;")
        self.count.setTextFormat(QtCore.Qt.PlainText)
        self.count.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.count.setObjectName("count")
        self.count_set = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.count_set.setGeometry(QtCore.QRect(950, 686, 0, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.count_set.setFont(font)
        self.count_set.setStyleSheet("background-color:white;border: 1px solid blue;")
        self.count_set.setAlignment(QtCore.Qt.AlignCenter)
        self.count_set.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.count_set.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.count_set.setMinimum(0.0)
        self.count_set.setMaximum(32000.0)
        self.count_set.setSingleStep(0.01)
        self.count_set.setObjectName("count_set")
        self.count_set_button = QtWidgets.QPushButton(self.centralwidget)
        self.count_set_button.setGeometry(QtCore.QRect(950, 686, 0, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.count_set_button.setFont(font)
        self.count_set_button.setStyleSheet("color: white; background-color: #0968b0;")
        self.count_set_button.setObjectName("count_set_button")
        self.CSYNC = QtWidgets.QLabel(self.centralwidget)
        self.CSYNC.setEnabled(False)
        self.CSYNC.setGeometry(QtCore.QRect(1214, 485, 31, 61))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(10)
        self.CSYNC.setFont(font)
        self.CSYNC.setStyleSheet("background-color: red;\n"
"color: white;\n"
"border: 1px solid white;")
        self.CSYNC.setTextFormat(QtCore.Qt.PlainText)
        self.CSYNC.setAlignment(QtCore.Qt.AlignCenter)
        self.CSYNC.setObjectName("CSYNC")
        self.cmdbg = QtWidgets.QFrame(self.centralwidget)
        self.cmdbg.setGeometry(QtCore.QRect(980, 555, 265, 417))
        self.cmdbg.setAcceptDrops(False)
        self.cmdbg.setAutoFillBackground(False)
        self.cmdbg.setStyleSheet("color:white;\n"
"background-color:transparent;\n"
"")
        self.cmdbg.setFrameShape(QtWidgets.QFrame.Box)
        self.cmdbg.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cmdbg.setObjectName("cmdbg")
        self.stop_button = QtWidgets.QPushButton(self.cmdbg)
        self.stop_button.setGeometry(QtCore.QRect(20, 20, 221, 41))
        self.stop_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.stop_button.setFont(font)
        self.stop_button.setStyleSheet("color: white;\n"
"background-color:#B02109;")
        self.stop_button.setCheckable(True)
        self.stop_button.setObjectName("stop_button")
        self.f1_button = QtWidgets.QPushButton(self.cmdbg)
        self.f1_button.setGeometry(QtCore.QRect(20, 70, 41, 41))
        self.f1_button.setMaximumSize(QtCore.QSize(216, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.f1_button.setFont(font)
        self.f1_button.setStyleSheet("color:white;background-color:#B02109;")
        self.f1_button.setCheckable(True)
        self.f1_button.setObjectName("f1_button")
        self.f2_button = QtWidgets.QPushButton(self.cmdbg)
        self.f2_button.setGeometry(QtCore.QRect(200, 70, 41, 41))
        self.f2_button.setMaximumSize(QtCore.QSize(216, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.f2_button.setFont(font)
        self.f2_button.setStyleSheet("color:white;background-color:#B02109;")
        self.f2_button.setCheckable(True)
        self.f2_button.setObjectName("f2_button")
        self.fire_button = QtWidgets.QPushButton(self.cmdbg)
        self.fire_button.setGeometry(QtCore.QRect(20, 70, 221, 41))
        self.fire_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.fire_button.setFont(font)
        self.fire_button.setStyleSheet("color:white;background-color:#B02109;")
        self.fire_button.setCheckable(True)
        self.fire_button.setObjectName("fire_button")
        self.arm_button = QtWidgets.QPushButton(self.cmdbg)
        self.arm_button.setGeometry(QtCore.QRect(130, 130, 111, 41))
        self.arm_button.setMaximumSize(QtCore.QSize(216, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.arm_button.setFont(font)
        self.arm_button.setStyleSheet("color:white;background-color: #0968b0;")
        self.arm_button.setCheckable(True)
        self.arm_button.setChecked(False)
        self.arm_button.setObjectName("arm_button")
        self.count_button = QtWidgets.QPushButton(self.cmdbg)
        self.count_button.setGeometry(QtCore.QRect(20, 130, 111, 41))
        self.count_button.setMaximumSize(QtCore.QSize(216, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.count_button.setFont(font)
        self.count_button.setStyleSheet("color:white;background-color: #0968b0;")
        self.count_button.setCheckable(True)
        self.count_button.setChecked(False)
        self.count_button.setObjectName("count_button")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.cmdbg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 172, 221, 226))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.testdef_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.testdef_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.testdef_button.setFont(font)
        self.testdef_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.testdef_button.setCheckable(False)
        self.testdef_button.setDefault(False)
        self.testdef_button.setFlat(False)
        self.testdef_button.setObjectName("testdef_button")
        self.verticalLayout.addWidget(self.testdef_button)
        self.log_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.log_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.log_button.setFont(font)
        self.log_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.log_button.setCheckable(True)
        self.log_button.setDefault(False)
        self.log_button.setFlat(False)
        self.log_button.setObjectName("log_button")
        self.verticalLayout.addWidget(self.log_button)
        self.newplot_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.newplot_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.newplot_button.setFont(font)
        self.newplot_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.newplot_button.setCheckable(False)
        self.newplot_button.setDefault(False)
        self.newplot_button.setFlat(False)
        self.newplot_button.setObjectName("newplot_button")
        self.verticalLayout.addWidget(self.newplot_button)
        self.plotfreeze_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plotfreeze_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.plotfreeze_button.setFont(font)
        self.plotfreeze_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.plotfreeze_button.setCheckable(True)
        self.plotfreeze_button.setDefault(False)
        self.plotfreeze_button.setFlat(False)
        self.plotfreeze_button.setObjectName("plotfreeze_button")
        self.verticalLayout.addWidget(self.plotfreeze_button)
        self.stopplots_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stopplots_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.stopplots_button.setFont(font)
        self.stopplots_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.stopplots_button.setCheckable(False)
        self.stopplots_button.setDefault(False)
        self.stopplots_button.setFlat(False)
        self.stopplots_button.setObjectName("stopplots_button")
        self.verticalLayout.addWidget(self.stopplots_button)
        self.upload_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.upload_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.upload_button.setFont(font)
        self.upload_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.upload_button.setCheckable(False)
        self.upload_button.setDefault(False)
        self.upload_button.setFlat(False)
        self.upload_button.setObjectName("upload_button")
        self.verticalLayout.addWidget(self.upload_button)
        self.reconnect_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reconnect_button.setMinimumSize(QtCore.QSize(0, 0))
        self.reconnect_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.reconnect_button.setFont(font)
        self.reconnect_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.reconnect_button.setCheckable(False)
        self.reconnect_button.setChecked(False)
        self.reconnect_button.setDefault(False)
        self.reconnect_button.setFlat(False)
        self.reconnect_button.setObjectName("reconnect_button")
        self.verticalLayout.addWidget(self.reconnect_button)
        self.reset_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.reset_button.setMinimumSize(QtCore.QSize(0, 0))
        self.reset_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet("color: white;\n"
"background-color: #083044;\n"
"")
        self.reset_button.setCheckable(False)
        self.reset_button.setChecked(False)
        self.reset_button.setDefault(False)
        self.reset_button.setFlat(False)
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout.addWidget(self.reset_button)
        self.arm_state = QtWidgets.QLabel(self.cmdbg)
        self.arm_state.setEnabled(False)
        self.arm_state.setGeometry(QtCore.QRect(132, 130, 109, 2))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(10)
        self.arm_state.setFont(font)
        self.arm_state.setStyleSheet("background-color: white;")
        self.arm_state.setText("")
        self.arm_state.setTextFormat(QtCore.Qt.PlainText)
        self.arm_state.setAlignment(QtCore.Qt.AlignCenter)
        self.arm_state.setObjectName("arm_state")
        self.stop_state = QtWidgets.QLabel(self.cmdbg)
        self.stop_state.setEnabled(False)
        self.stop_state.setGeometry(QtCore.QRect(21, 20, 220, 2))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(10)
        self.stop_state.setFont(font)
        self.stop_state.setStyleSheet("background-color: white;")
        self.stop_state.setText("")
        self.stop_state.setTextFormat(QtCore.Qt.PlainText)
        self.stop_state.setAlignment(QtCore.Qt.AlignCenter)
        self.stop_state.setObjectName("stop_state")
        self.fire_button.raise_()
        self.stop_button.raise_()
        self.f1_button.raise_()
        self.f2_button.raise_()
        self.arm_button.raise_()
        self.count_button.raise_()
        self.verticalLayoutWidget.raise_()
        self.arm_state.raise_()
        self.stop_state.raise_()
        self.f2 = QtWidgets.QPushButton(self.centralwidget)
        self.f2.setGeometry(QtCore.QRect(980, 625, 0, 41))
        self.f2.setMaximumSize(QtCore.QSize(216, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.f2.setFont(font)
        self.f2.setStyleSheet("color:white;background-color:#B02109;")
        self.f2.setCheckable(True)
        self.f2.setObjectName("f2")
        self.f1 = QtWidgets.QPushButton(self.centralwidget)
        self.f1.setGeometry(QtCore.QRect(980, 585, 0, 41))
        self.f1.setMaximumSize(QtCore.QSize(216, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.f1.setFont(font)
        self.f1.setStyleSheet("color:white;background-color:#B02109;")
        self.f1.setCheckable(True)
        self.f1.setObjectName("f1")
        self.procbg = QtWidgets.QFrame(self.centralwidget)
        self.procbg.setGeometry(QtCore.QRect(980, 65, 265, 411))
        self.procbg.setAcceptDrops(False)
        self.procbg.setAutoFillBackground(False)
        self.procbg.setStyleSheet("color:white;\n"
"background-color:transparent;\n"
"")
        self.procbg.setFrameShape(QtWidgets.QFrame.Box)
        self.procbg.setFrameShadow(QtWidgets.QFrame.Plain)
        self.procbg.setObjectName("procbg")
        self.proc_next_button = QtWidgets.QPushButton(self.procbg)
        self.proc_next_button.setGeometry(QtCore.QRect(205, 10, 51, 31))
        self.proc_next_button.setMaximumSize(QtCore.QSize(216, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.proc_next_button.setFont(font)
        self.proc_next_button.setStyleSheet("color:white;background-color: #0968b0;")
        self.proc_next_button.setCheckable(False)
        self.proc_next_button.setChecked(False)
        self.proc_next_button.setObjectName("proc_next_button")
        self.proc_set = QtWidgets.QDoubleSpinBox(self.procbg)
        self.proc_set.setGeometry(QtCore.QRect(130, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.proc_set.setFont(font)
        self.proc_set.setStyleSheet("border: 1px solid #0295ff;")
        self.proc_set.setAlignment(QtCore.Qt.AlignCenter)
        self.proc_set.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.proc_set.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.proc_set.setMinimum(0.0)
        self.proc_set.setMaximum(32000.0)
        self.proc_set.setSingleStep(0.01)
        self.proc_set.setObjectName("proc_set")
        self.label_2 = QtWidgets.QLabel(self.procbg)
        self.label_2.setGeometry(QtCore.QRect(5, 15, 121, 26))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white; background-color:transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.procedures = QtWidgets.QWidget(self.procbg)
        self.procedures.setGeometry(QtCore.QRect(2, 41, 260, 369))
        self.procedures.setObjectName("procedures")
        self.proc_grad_top = QtWidgets.QLabel(self.procbg)
        self.proc_grad_top.setGeometry(QtCore.QRect(1, 2, 262, 119))
        self.proc_grad_top.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.517075, y1:0, x2:0.493, y2:0.9885, stop:0 rgba(4, 26, 37, 255), stop:1 rgba(255, 255, 255, 0))")
        self.proc_grad_top.setText("")
        self.proc_grad_top.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.proc_grad_top.setObjectName("proc_grad_top")
        self.procedures.raise_()
        self.proc_grad_top.raise_()
        self.label_2.raise_()
        self.proc_next_button.raise_()
        self.proc_set.raise_()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1160, 15, 86, 31))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white; background-color:transparent;")
        self.label.setObjectName("label")
        self._mtr_ = QtWidgets.QLabel(self.centralwidget)
        self._mtr_.setGeometry(QtCore.QRect(476, 521, 131, 281))
        self._mtr_.setStyleSheet("background-color:transparent")
        self._mtr_.setText("")
        self._mtr_.setPixmap(QtGui.QPixmap("graphics/motor.png"))
        self._mtr_.setObjectName("_mtr_")
        self.flames = QtWidgets.QLabel(self.centralwidget)
        self.flames.setGeometry(QtCore.QRect(480, 770, 131, 131))
        self.flames.setStyleSheet("background-color:transparent")
        self.flames.setText("")
        self.flames.setPixmap(QtGui.QPixmap("graphics/burnbabyburn.png"))
        self.flames.setObjectName("flames")
        self.p1probe_p1 = QtWidgets.QLabel(self.centralwidget)
        self.p1probe_p1.setGeometry(QtCore.QRect(588, 540, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(14)
        self.p1probe_p1.setFont(font)
        self.p1probe_p1.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.p1probe_p1.setObjectName("p1probe_p1")
        self.t1probe_t1 = QtWidgets.QLabel(self.centralwidget)
        self.t1probe_t1.setGeometry(QtCore.QRect(588, 580, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(14)
        self.t1probe_t1.setFont(font)
        self.t1probe_t1.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.t1probe_t1.setObjectName("t1probe_t1")
        self.gprobe_g = QtWidgets.QLabel(self.centralwidget)
        self.gprobe_g.setGeometry(QtCore.QRect(476, 540, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(14)
        self.gprobe_g.setFont(font)
        self.gprobe_g.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.gprobe_g.setObjectName("gprobe_g")
        self.t2probe_t2 = QtWidgets.QLabel(self.centralwidget)
        self.t2probe_t2.setGeometry(QtCore.QRect(472, 782, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(14)
        self.t2probe_t2.setFont(font)
        self.t2probe_t2.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.t2probe_t2.setObjectName("t2probe_t2")
        self.Rbool = QtWidgets.QLabel(self.centralwidget)
        self.Rbool.setGeometry(QtCore.QRect(522, 420, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.Rbool.setFont(font)
        self.Rbool.setStyleSheet("color: white;\n"
"background-color: transparent;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.Rbool.setTextFormat(QtCore.Qt.PlainText)
        self.Rbool.setScaledContents(False)
        self.Rbool.setAlignment(QtCore.Qt.AlignCenter)
        self.Rbool.setIndent(-1)
        self.Rbool.setObjectName("Rbool")
        self.Rnum = QtWidgets.QLabel(self.centralwidget)
        self.Rnum.setGeometry(QtCore.QRect(452, 420, 71, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.Rnum.setFont(font)
        self.Rnum.setStyleSheet("color: white;\n"
"background-color: transparent;\n"
"border-radius: 2px;\n"
"border: 1px solid white;")
        self.Rnum.setTextFormat(QtCore.Qt.PlainText)
        self.Rnum.setScaledContents(False)
        self.Rnum.setAlignment(QtCore.Qt.AlignCenter)
        self.Rnum.setIndent(-1)
        self.Rnum.setObjectName("Rnum")
        self.Rnumbar = QtWidgets.QLabel(self.centralwidget)
        self.Rnumbar.setGeometry(QtCore.QRect(453, 420, 71, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.Rnumbar.setFont(font)
        self.Rnumbar.setStyleSheet("border-radius:3px;\n"
"background-color: #1f3645;\n"
"")
        self.Rnumbar.setText("")
        self.Rnumbar.setTextFormat(QtCore.Qt.PlainText)
        self.Rnumbar.setScaledContents(False)
        self.Rnumbar.setAlignment(QtCore.Qt.AlignCenter)
        self.Rnumbar.setIndent(-1)
        self.Rnumbar.setObjectName("Rnumbar")
        self.R_u1 = QtWidgets.QLabel(self.centralwidget)
        self.R_u1.setGeometry(QtCore.QRect(444, 435, 12, 12))
        self.R_u1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.R_u1.setFont(font)
        self.R_u1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.R_u1.setObjectName("R_u1")
        self.u2 = QtWidgets.QLabel(self.centralwidget)
        self.u2.setGeometry(QtCore.QRect(334, 369, 47, 47))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.u2.setFont(font)
        self.u2.setStyleSheet("color: #2d3438;\n"
"background-color: white;\n"
"border-radius: 2px;")
        self.u2.setTextFormat(QtCore.Qt.PlainText)
        self.u2.setScaledContents(False)
        self.u2.setAlignment(QtCore.Qt.AlignCenter)
        self.u2.setIndent(-1)
        self.u2.setObjectName("u2")
        self.u2_I = QtWidgets.QLabel(self.centralwidget)
        self.u2_I.setGeometry(QtCore.QRect(378, 387, 12, 12))
        self.u2_I.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.u2_I.setFont(font)
        self.u2_I.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.u2_I.setObjectName("u2_I")
        self.B = QtWidgets.QLabel(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(520, 330, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.B.setFont(font)
        self.B.setStyleSheet("color: white;\n"
"background-color: transparent;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.B.setTextFormat(QtCore.Qt.PlainText)
        self.B.setScaledContents(False)
        self.B.setAlignment(QtCore.Qt.AlignCenter)
        self.B.setIndent(-1)
        self.B.setObjectName("B")
        self.B_u1 = QtWidgets.QLabel(self.centralwidget)
        self.B_u1.setGeometry(QtCore.QRect(512, 345, 12, 12))
        self.B_u1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.B_u1.setFont(font)
        self.B_u1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.B_u1.setObjectName("B_u1")
        self.u1 = QtWidgets.QLabel(self.centralwidget)
        self.u1.setGeometry(QtCore.QRect(334, 252, 47, 47))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.u1.setFont(font)
        self.u1.setStyleSheet("color: #2d3438;\n"
"background-color: white;\n"
"border-radius: 2px;")
        self.u1.setTextFormat(QtCore.Qt.PlainText)
        self.u1.setScaledContents(False)
        self.u1.setAlignment(QtCore.Qt.AlignCenter)
        self.u1.setIndent(-1)
        self.u1.setObjectName("u1")
        self.A = QtWidgets.QLabel(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(520, 240, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.A.setFont(font)
        self.A.setStyleSheet("color: white;\n"
"background-color: transparent;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.A.setTextFormat(QtCore.Qt.PlainText)
        self.A.setScaledContents(False)
        self.A.setAlignment(QtCore.Qt.AlignCenter)
        self.A.setIndent(-1)
        self.A.setObjectName("A")
        self.u1_A = QtWidgets.QLabel(self.centralwidget)
        self.u1_A.setGeometry(QtCore.QRect(378, 255, 12, 12))
        self.u1_A.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.u1_A.setFont(font)
        self.u1_A.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.u1_A.setObjectName("u1_A")
        self.A_u1 = QtWidgets.QLabel(self.centralwidget)
        self.A_u1.setGeometry(QtCore.QRect(512, 254, 12, 12))
        self.A_u1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.A_u1.setFont(font)
        self.A_u1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.A_u1.setObjectName("A_u1")
        self.u1_B = QtWidgets.QLabel(self.centralwidget)
        self.u1_B.setGeometry(QtCore.QRect(378, 270, 12, 12))
        self.u1_B.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.u1_B.setFont(font)
        self.u1_B.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.u1_B.setObjectName("u1_B")
        self.hdcsunderscore = QtWidgets.QFrame(self.centralwidget)
        self.hdcsunderscore.setGeometry(QtCore.QRect(1159, 50, 87, 5))
        self.hdcsunderscore.setMinimumSize(QtCore.QSize(0, 0))
        self.hdcsunderscore.setMaximumSize(QtCore.QSize(16777215, 5))
        self.hdcsunderscore.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.hdcsunderscore.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hdcsunderscore.setLineWidth(1)
        self.hdcsunderscore.setFrameShape(QtWidgets.QFrame.HLine)
        self.hdcsunderscore.setObjectName("hdcsunderscore")
        self.adcs = QtWidgets.QLabel(self.centralwidget)
        self.adcs.setGeometry(QtCore.QRect(178, 308, 99, 53))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.adcs.setFont(font)
        self.adcs.setStyleSheet("color: #2d3438;\n"
"background-color: white;\n"
"border-radius: 2px;")
        self.adcs.setTextFormat(QtCore.Qt.PlainText)
        self.adcs.setScaledContents(False)
        self.adcs.setAlignment(QtCore.Qt.AlignCenter)
        self.adcs.setIndent(-1)
        self.adcs.setObjectName("adcs")
        self.adcs_u2 = QtWidgets.QLabel(self.centralwidget)
        self.adcs_u2.setGeometry(QtCore.QRect(224, 358, 12, 12))
        self.adcs_u2.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.adcs_u2.setFont(font)
        self.adcs_u2.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.adcs_u2.setObjectName("adcs_u2")
        self.adcs_u1 = QtWidgets.QLabel(self.centralwidget)
        self.adcs_u1.setGeometry(QtCore.QRect(222, 298, 12, 12))
        self.adcs_u1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.adcs_u1.setFont(font)
        self.adcs_u1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.adcs_u1.setObjectName("adcs_u1")
        self.fa1 = QtWidgets.QLabel(self.centralwidget)
        self.fa1.setGeometry(QtCore.QRect(345, 314, 16, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.fa1.setFont(font)
        self.fa1.setStyleSheet("color: #dd0000;background:transparent;")
        self.fa1.setAlignment(QtCore.Qt.AlignCenter)
        self.fa1.setObjectName("fa1")
        self.fa2 = QtWidgets.QLabel(self.centralwidget)
        self.fa2.setGeometry(QtCore.QRect(360, 314, 16, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.fa2.setFont(font)
        self.fa2.setStyleSheet("color: #dd0000;background:transparent;")
        self.fa2.setAlignment(QtCore.Qt.AlignCenter)
        self.fa2.setObjectName("fa2")
        self.dcs = QtWidgets.QLabel(self.centralwidget)
        self.dcs.setGeometry(QtCore.QRect(95, 75, 16, 56))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.dcs.setFont(font)
        self.dcs.setStyleSheet("color: #2d3438;background:transparent;")
        self.dcs.setAlignment(QtCore.Qt.AlignCenter)
        self.dcs.setObjectName("dcs")
        self.N2O = QtWidgets.QLabel(self.centralwidget)
        self.N2O.setGeometry(QtCore.QRect(490, 90, 100, 100))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(16)
        self.N2O.setFont(font)
        self.N2O.setStyleSheet("color: white;\n"
"background-color: transparent;\n"
"border: 1px solid white;\n"
"border-radius: 50px;\n"
"")
        self.N2O.setTextFormat(QtCore.Qt.PlainText)
        self.N2O.setScaledContents(False)
        self.N2O.setAlignment(QtCore.Qt.AlignCenter)
        self.N2O.setIndent(-1)
        self.N2O.setObjectName("N2O")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(530, 133, 21, 21))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: transparent;\n"
"color: white;")
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setScaledContents(False)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setIndent(-1)
        self.label_12.setObjectName("label_12")
        self.N2O_P0 = QtWidgets.QFrame(self.centralwidget)
        self.N2O_P0.setGeometry(QtCore.QRect(585, 120, 16, 5))
        self.N2O_P0.setMinimumSize(QtCore.QSize(0, 0))
        self.N2O_P0.setMaximumSize(QtCore.QSize(16777215, 5))
        self.N2O_P0.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.N2O_P0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.N2O_P0.setLineWidth(1)
        self.N2O_P0.setFrameShape(QtWidgets.QFrame.HLine)
        self.N2O_P0.setObjectName("N2O_P0")
        self.N2O_T0 = QtWidgets.QFrame(self.centralwidget)
        self.N2O_T0.setGeometry(QtCore.QRect(590, 150, 8, 5))
        self.N2O_T0.setMinimumSize(QtCore.QSize(0, 0))
        self.N2O_T0.setMaximumSize(QtCore.QSize(16777215, 5))
        self.N2O_T0.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.N2O_T0.setFrameShadow(QtWidgets.QFrame.Plain)
        self.N2O_T0.setLineWidth(1)
        self.N2O_T0.setFrameShape(QtWidgets.QFrame.HLine)
        self.N2O_T0.setObjectName("N2O_T0")
        self.I = QtWidgets.QLabel(self.centralwidget)
        self.I.setGeometry(QtCore.QRect(629, 403, 41, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(18)
        self.I.setFont(font)
        self.I.setStyleSheet("color: white;\n"
"background-color: transparent;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.I.setTextFormat(QtCore.Qt.PlainText)
        self.I.setScaledContents(False)
        self.I.setAlignment(QtCore.Qt.AlignCenter)
        self.I.setIndent(-1)
        self.I.setObjectName("I")
        self.I_u2 = QtWidgets.QLabel(self.centralwidget)
        self.I_u2.setGeometry(QtCore.QRect(644, 393, 12, 12))
        self.I_u2.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.I_u2.setFont(font)
        self.I_u2.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.I_u2.setObjectName("I_u2")
        self.I_v2 = QtWidgets.QLabel(self.centralwidget)
        self.I_v2.setGeometry(QtCore.QRect(668, 412, 12, 12))
        self.I_v2.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.I_v2.setFont(font)
        self.I_v2.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.I_v2.setObjectName("I_v2")
        self.B_v1 = QtWidgets.QLabel(self.centralwidget)
        self.B_v1.setGeometry(QtCore.QRect(559, 345, 12, 12))
        self.B_v1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.B_v1.setFont(font)
        self.B_v1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.B_v1.setObjectName("B_v1")
        self.A_v1 = QtWidgets.QLabel(self.centralwidget)
        self.A_v1.setGeometry(QtCore.QRect(559, 255, 12, 12))
        self.A_v1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.A_v1.setFont(font)
        self.A_v1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.A_v1.setObjectName("A_v1")
        self.v2 = QtWidgets.QLabel(self.centralwidget)
        self.v2.setGeometry(QtCore.QRect(705, 402, 71, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.v2.setFont(font)
        self.v2.setStyleSheet("color: white;\n"
"background-color: #5e5e5e;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.v2.setTextFormat(QtCore.Qt.PlainText)
        self.v2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.v2.setObjectName("v2")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(756, 402, 26, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.v1 = QtWidgets.QLabel(self.centralwidget)
        self.v1.setGeometry(QtCore.QRect(705, 335, 71, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.v1.setFont(font)
        self.v1.setStyleSheet("color: white;\n"
"background-color: #5e5e5e;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.v1.setTextFormat(QtCore.Qt.PlainText)
        self.v1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.v1.setObjectName("v1")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(756, 335, 26, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.i1 = QtWidgets.QLabel(self.centralwidget)
        self.i1.setGeometry(QtCore.QRect(775, 335, 71, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.i1.setFont(font)
        self.i1.setStyleSheet("color: white;\n"
"background-color: #5e5e5e;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.i1.setTextFormat(QtCore.Qt.PlainText)
        self.i1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.i1.setObjectName("i1")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(826, 335, 26, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(826, 402, 26, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: white;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.i2 = QtWidgets.QLabel(self.centralwidget)
        self.i2.setGeometry(QtCore.QRect(775, 402, 71, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.i2.setFont(font)
        self.i2.setStyleSheet("color: white;\n"
"background-color: #5e5e5e;\n"
"border: 1px solid white;\n"
"border-radius: 2px;\n"
"")
        self.i2.setTextFormat(QtCore.Qt.PlainText)
        self.i2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.i2.setObjectName("i2")
        self.u3disconn = QtWidgets.QLabel(self.centralwidget)
        self.u3disconn.setGeometry(QtCore.QRect(836, 66, 136, 16))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(12)
        self.u3disconn.setFont(font)
        self.u3disconn.setStyleSheet("background-color: transparent;\n"
"color: #ffae00;")
        self.u3disconn.setTextFormat(QtCore.Qt.PlainText)
        self.u3disconn.setScaledContents(False)
        self.u3disconn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.u3disconn.setIndent(-1)
        self.u3disconn.setObjectName("u3disconn")
        self.u4disconn = QtWidgets.QLabel(self.centralwidget)
        self.u4disconn.setGeometry(QtCore.QRect(836, 86, 136, 16))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(12)
        self.u4disconn.setFont(font)
        self.u4disconn.setStyleSheet("background-color: transparent;\n"
"color: #ffae00;")
        self.u4disconn.setTextFormat(QtCore.Qt.PlainText)
        self.u4disconn.setScaledContents(False)
        self.u4disconn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.u4disconn.setIndent(-1)
        self.u4disconn.setObjectName("u4disconn")
        self.pwrdisconn = QtWidgets.QLabel(self.centralwidget)
        self.pwrdisconn.setGeometry(QtCore.QRect(836, 106, 136, 16))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(12)
        self.pwrdisconn.setFont(font)
        self.pwrdisconn.setStyleSheet("background-color: transparent;\n"
"color: #ffae00;")
        self.pwrdisconn.setTextFormat(QtCore.Qt.PlainText)
        self.pwrdisconn.setScaledContents(False)
        self.pwrdisconn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwrdisconn.setIndent(-1)
        self.pwrdisconn.setObjectName("pwrdisconn")
        self.v2_I = QtWidgets.QLabel(self.centralwidget)
        self.v2_I.setGeometry(QtCore.QRect(696, 412, 12, 12))
        self.v2_I.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.v2_I.setFont(font)
        self.v2_I.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.v2_I.setObjectName("v2_I")
        self.u2_2 = QtWidgets.QLabel(self.centralwidget)
        self.u2_2.setEnabled(True)
        self.u2_2.setGeometry(QtCore.QRect(910, 501, 36, 31))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.u2_2.setFont(font)
        self.u2_2.setStyleSheet("color: #2d3438;\n"
"background-color: white;\n"
"border-radius: 2px;")
        self.u2_2.setTextFormat(QtCore.Qt.PlainText)
        self.u2_2.setScaledContents(False)
        self.u2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.u2_2.setIndent(-1)
        self.u2_2.setObjectName("u2_2")
        self.u2_f1 = QtWidgets.QLabel(self.centralwidget)
        self.u2_f1.setEnabled(True)
        self.u2_f1.setGeometry(QtCore.QRect(923, 530, 12, 12))
        self.u2_f1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.u2_f1.setFont(font)
        self.u2_f1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.u2_f1.setObjectName("u2_f1")
        self.f1_u2 = QtWidgets.QLabel(self.centralwidget)
        self.f1_u2.setEnabled(True)
        self.f1_u2.setGeometry(QtCore.QRect(923, 574, 12, 12))
        self.f1_u2.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.f1_u2.setFont(font)
        self.f1_u2.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.f1_u2.setObjectName("f1_u2")
        self.v1_A = QtWidgets.QLabel(self.centralwidget)
        self.v1_A.setGeometry(QtCore.QRect(735, 325, 12, 12))
        self.v1_A.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.v1_A.setFont(font)
        self.v1_A.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.v1_A.setObjectName("v1_A")
        self.I_electrode = QtWidgets.QLabel(self.centralwidget)
        self.I_electrode.setGeometry(QtCore.QRect(644, 442, 12, 12))
        self.I_electrode.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.I_electrode.setFont(font)
        self.I_electrode.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.I_electrode.setObjectName("I_electrode")
        self.v1_B = QtWidgets.QLabel(self.centralwidget)
        self.v1_B.setGeometry(QtCore.QRect(696, 345, 12, 12))
        self.v1_B.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.v1_B.setFont(font)
        self.v1_B.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.v1_B.setObjectName("v1_B")
        self.v2_f1 = QtWidgets.QLabel(self.centralwidget)
        self.v2_f1.setGeometry(QtCore.QRect(909, 412, 12, 12))
        self.v2_f1.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.v2_f1.setFont(font)
        self.v2_f1.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.v2_f1.setObjectName("v2_f1")
        self.f1_v2 = QtWidgets.QLabel(self.centralwidget)
        self.f1_v2.setEnabled(True)
        self.f1_v2.setGeometry(QtCore.QRect(950, 574, 12, 12))
        self.f1_v2.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.f1_v2.setFont(font)
        self.f1_v2.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.f1_v2.setObjectName("f1_v2")
        self.count_set_button_expand = QtWidgets.QPushButton(self.centralwidget)
        self.count_set_button_expand.setGeometry(QtCore.QRect(950, 686, 31, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.count_set_button_expand.setFont(font)
        self.count_set_button_expand.setStyleSheet("color: white;\n"
"background-color: rgba(78, 96, 131, 50);")
        self.count_set_button_expand.setObjectName("count_set_button_expand")
        self.u2_adcs = QtWidgets.QLabel(self.centralwidget)
        self.u2_adcs.setGeometry(QtCore.QRect(326, 386, 12, 12))
        self.u2_adcs.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.u2_adcs.setFont(font)
        self.u2_adcs.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.u2_adcs.setObjectName("u2_adcs")
        self.u1_adcs = QtWidgets.QLabel(self.centralwidget)
        self.u1_adcs.setGeometry(QtCore.QRect(326, 270, 12, 12))
        self.u1_adcs.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.u1_adcs.setFont(font)
        self.u1_adcs.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.u1_adcs.setObjectName("u1_adcs")
        self.electrode_I = QtWidgets.QLabel(self.centralwidget)
        self.electrode_I.setGeometry(QtCore.QRect(553, 514, 12, 12))
        self.electrode_I.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.electrode_I.setFont(font)
        self.electrode_I.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.electrode_I.setObjectName("electrode_I")
        self.u1_R = QtWidgets.QLabel(self.centralwidget)
        self.u1_R.setGeometry(QtCore.QRect(378, 284, 12, 12))
        self.u1_R.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.u1_R.setFont(font)
        self.u1_R.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.u1_R.setObjectName("u1_R")
        self.proc_grad_bot = QtWidgets.QLabel(self.centralwidget)
        self.proc_grad_bot.setGeometry(QtCore.QRect(982, 382, 262, 93))
        self.proc_grad_bot.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.532, y1:1, x2:0.522, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 0));")
        self.proc_grad_bot.setText("")
        self.proc_grad_bot.setObjectName("proc_grad_bot")
        self.xyfbg = QtWidgets.QFrame(self.centralwidget)
        self.xyfbg.setGeometry(QtCore.QRect(18, 574, 270, 216))
        self.xyfbg.setAcceptDrops(False)
        self.xyfbg.setAutoFillBackground(False)
        self.xyfbg.setStyleSheet("color:#2d3438;\n"
"background-color:transparent;")
        self.xyfbg.setFrameShape(QtWidgets.QFrame.Box)
        self.xyfbg.setFrameShadow(QtWidgets.QFrame.Plain)
        self.xyfbg.setObjectName("xyfbg")
        self.yflabel = QtWidgets.QFrame(self.xyfbg)
        self.yflabel.setGeometry(QtCore.QRect(135, 28, 1, 160))
        self.yflabel.setMinimumSize(QtCore.QSize(1, 0))
        self.yflabel.setMaximumSize(QtCore.QSize(3, 16777215))
        self.yflabel.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.yflabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yflabel.setLineWidth(3)
        self.yflabel.setFrameShape(QtWidgets.QFrame.VLine)
        self.yflabel.setObjectName("yflabel")
        self.xflabel = QtWidgets.QFrame(self.xyfbg)
        self.xflabel.setGeometry(QtCore.QRect(55, 108, 160, 5))
        self.xflabel.setMinimumSize(QtCore.QSize(0, 0))
        self.xflabel.setMaximumSize(QtCore.QSize(16777215, 5))
        self.xflabel.setStyleSheet("background-color:transparent;\n"
"color:#2d3438;\n"
"")
        self.xflabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.xflabel.setLineWidth(1)
        self.xflabel.setFrameShape(QtWidgets.QFrame.HLine)
        self.xflabel.setObjectName("xflabel")
        self.xf0 = QtWidgets.QLabel(self.xyfbg)
        self.xf0.setGeometry(QtCore.QRect(0, 102, 53, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.xf0.setFont(font)
        self.xf0.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.xf0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xf0.setObjectName("xf0")
        self.label_29 = QtWidgets.QLabel(self.xyfbg)
        self.label_29.setGeometry(QtCore.QRect(40, 102, 16, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_29.setObjectName("label_29")
        self.yf0 = QtWidgets.QLabel(self.xyfbg)
        self.yf0.setGeometry(QtCore.QRect(108, 0, 55, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.yf0.setFont(font)
        self.yf0.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.yf0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yf0.setObjectName("yf0")
        self.label_25 = QtWidgets.QLabel(self.xyfbg)
        self.label_25.setGeometry(QtCore.QRect(150, 0, 16, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_25.setObjectName("label_25")
        self.xf1 = QtWidgets.QLabel(self.xyfbg)
        self.xf1.setGeometry(QtCore.QRect(216, 102, 53, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.xf1.setFont(font)
        self.xf1.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.xf1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xf1.setObjectName("xf1")
        self.label_30 = QtWidgets.QLabel(self.xyfbg)
        self.label_30.setGeometry(QtCore.QRect(256, 102, 16, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_30.setObjectName("label_30")
        self.yf1 = QtWidgets.QLabel(self.xyfbg)
        self.yf1.setGeometry(QtCore.QRect(102, 194, 53, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.yf1.setFont(font)
        self.yf1.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.yf1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yf1.setObjectName("yf1")
        self.label_33 = QtWidgets.QLabel(self.xyfbg)
        self.label_33.setGeometry(QtCore.QRect(142, 194, 16, 17))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_33.setObjectName("label_33")
        self.it_adcs = QtWidgets.QLabel(self.centralwidget)
        self.it_adcs.setGeometry(QtCore.QRect(96, 182, 12, 12))
        self.it_adcs.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.it_adcs.setFont(font)
        self.it_adcs.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.it_adcs.setObjectName("it_adcs")
        self.adcs_it = QtWidgets.QLabel(self.centralwidget)
        self.adcs_it.setGeometry(QtCore.QRect(170, 328, 12, 12))
        self.adcs_it.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.adcs_it.setFont(font)
        self.adcs_it.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"")
        self.adcs_it.setObjectName("adcs_it")
        self.t1_t1probe = QtWidgets.QLabel(self.centralwidget)
        self.t1_t1probe.setGeometry(QtCore.QRect(648, 582, 12, 12))
        self.t1_t1probe.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.t1_t1probe.setFont(font)
        self.t1_t1probe.setStyleSheet("color:transparent;\n"
"background-color:transparent;\n"
"")
        self.t1_t1probe.setObjectName("t1_t1probe")
        self.p1_p1probe = QtWidgets.QLabel(self.centralwidget)
        self.p1_p1probe.setGeometry(QtCore.QRect(648, 544, 12, 12))
        self.p1_p1probe.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.p1_p1probe.setFont(font)
        self.p1_p1probe.setStyleSheet("color:transparent;\n"
"background-color:transparent;\n"
"")
        self.p1_p1probe.setObjectName("p1_p1probe")
        self.g_gprobe = QtWidgets.QLabel(self.centralwidget)
        self.g_gprobe.setGeometry(QtCore.QRect(432, 542, 12, 12))
        self.g_gprobe.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.g_gprobe.setFont(font)
        self.g_gprobe.setStyleSheet("color:transparent;\n"
"background-color:transparent;\n"
"")
        self.g_gprobe.setObjectName("g_gprobe")
        self.t2_t2probe = QtWidgets.QLabel(self.centralwidget)
        self.t2_t2probe.setGeometry(QtCore.QRect(410, 790, 12, 12))
        self.t2_t2probe.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.t2_t2probe.setFont(font)
        self.t2_t2probe.setStyleSheet("color:transparent;\n"
"background-color:transparent;\n"
"")
        self.t2_t2probe.setObjectName("t2_t2probe")
        self.motor_Rbool = QtWidgets.QLabel(self.centralwidget)
        self.motor_Rbool.setGeometry(QtCore.QRect(536, 518, 12, 12))
        self.motor_Rbool.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.motor_Rbool.setFont(font)
        self.motor_Rbool.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.motor_Rbool.setObjectName("motor_Rbool")
        self.Rbool_motor = QtWidgets.QLabel(self.centralwidget)
        self.Rbool_motor.setGeometry(QtCore.QRect(536, 454, 12, 12))
        self.Rbool_motor.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.Rbool_motor.setFont(font)
        self.Rbool_motor.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.Rbool_motor.setObjectName("Rbool_motor")
        self.R_B = QtWidgets.QLabel(self.centralwidget)
        self.R_B.setGeometry(QtCore.QRect(536, 412, 12, 12))
        self.R_B.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.R_B.setFont(font)
        self.R_B.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.R_B.setObjectName("R_B")
        self.B_R = QtWidgets.QLabel(self.centralwidget)
        self.B_R.setGeometry(QtCore.QRect(536, 366, 12, 12))
        self.B_R.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.B_R.setFont(font)
        self.B_R.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.B_R.setObjectName("B_R")
        self.B_A = QtWidgets.QLabel(self.centralwidget)
        self.B_A.setGeometry(QtCore.QRect(534, 324, 12, 12))
        self.B_A.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.B_A.setFont(font)
        self.B_A.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.B_A.setObjectName("B_A")
        self.A_B = QtWidgets.QLabel(self.centralwidget)
        self.A_B.setGeometry(QtCore.QRect(534, 276, 12, 12))
        self.A_B.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.A_B.setFont(font)
        self.A_B.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.A_B.setObjectName("A_B")
        self.A_n2o = QtWidgets.QLabel(self.centralwidget)
        self.A_n2o.setGeometry(QtCore.QRect(534, 232, 12, 12))
        self.A_n2o.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.A_n2o.setFont(font)
        self.A_n2o.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.A_n2o.setObjectName("A_n2o")
        self.n2o_A = QtWidgets.QLabel(self.centralwidget)
        self.n2o_A.setGeometry(QtCore.QRect(534, 186, 12, 12))
        self.n2o_A.setMaximumSize(QtCore.QSize(12, 12))
        font = QtGui.QFont()
        font.setFamily("Wingdings")
        font.setPointSize(10)
        self.n2o_A.setFont(font)
        self.n2o_A.setStyleSheet("color:transparent;\n"
"background-color:transparent;")
        self.n2o_A.setObjectName("n2o_A")
        self.livelog = QtWidgets.QTextEdit(self.centralwidget)
        self.livelog.setGeometry(QtCore.QRect(980, 842, 0, 85))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        self.livelog.setFont(font)
        self.livelog.setStyleSheet("color: white; \n"
"background-color: transparent;\n"
"border: 1px solid rgba(78, 96, 131, 50);;")
        self.livelog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.livelog.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.livelog.setUndoRedoEnabled(True)
        self.livelog.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.livelog.setReadOnly(True)
        self.livelog.setObjectName("livelog")
        self.livelog_expand = QtWidgets.QPushButton(self.centralwidget)
        self.livelog_expand.setGeometry(QtCore.QRect(950, 866, 31, 37))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.livelog_expand.setFont(font)
        self.livelog_expand.setStyleSheet("color: white;\n"
"background-color: rgba(78, 96, 131, 50);")
        self.livelog_expand.setObjectName("livelog_expand")
        self.b2_toggle = QtWidgets.QPushButton(self.centralwidget)
        self.b2_toggle.setGeometry(QtCore.QRect(844, 402, 67, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.b2_toggle.setFont(font)
        self.b2_toggle.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: white;\n"
"border-radius: 2px;\n"
"border: 1px solid white;\n"
"}\n"
"QPushButton::checked{\n"
"  background-color: rgba(78, 96, 131, 50);\n"
"  color: white;\n"
"  border-radius: 2px;\n"
"  border: 1px solid white;\n"
"}")
        self.b2_toggle.setCheckable(True)
        self.b2_toggle.setFlat(True)
        self.b2_toggle.setObjectName("b2_toggle")
        self.b1_toggle = QtWidgets.QPushButton(self.centralwidget)
        self.b1_toggle.setGeometry(QtCore.QRect(844, 335, 67, 36))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.b1_toggle.setFont(font)
        self.b1_toggle.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: white;\n"
"border-radius: 2px;\n"
"border: 1px solid white;\n"
"}\n"
"QPushButton::checked{\n"
"  background-color: rgba(78, 96, 131, 50);\n"
"  color: white;\n"
"  border-radius: 2px;\n"
"  border: 1px solid white;\n"
"}")
        self.b1_toggle.setCheckable(True)
        self.b1_toggle.setFlat(True)
        self.b1_toggle.setObjectName("b1_toggle")
        self.plotDropFrame = QtWidgets.QFrame(self.centralwidget)
        self.plotDropFrame.setGeometry(QtCore.QRect(6, 890, 663, 81))
        self.plotDropFrame.setStyleSheet("background-color: rgba(4, 26, 37, 255);")
        self.plotDropFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plotDropFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotDropFrame.setObjectName("plotDropFrame")
        self.t0 = QtWidgets.QLabel(self.centralwidget)
        self.t0.setGeometry(QtCore.QRect(600, 143, 87, 39))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.t0.setFont(font)
        self.t0.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.t0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.t0.setObjectName("t0")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(664, 148, 16, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_8.setObjectName("label_8")
        self.p0 = QtWidgets.QLabel(self.centralwidget)
        self.p0.setGeometry(QtCore.QRect(600, 104, 101, 39))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.p0.setFont(font)
        self.p0.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.p0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.p0.setObjectName("p0")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(666, 110, 27, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.v0 = QtWidgets.QLabel(self.centralwidget)
        self.v0.setGeometry(QtCore.QRect(600, 80, 51, 23))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.v0.setFont(font)
        self.v0.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.v0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.v0.setObjectName("v0")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(640, 80, 16, 23))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_9.setObjectName("label_9")
        self.dt = QtWidgets.QLabel(self.centralwidget)
        self.dt.setGeometry(QtCore.QRect(64, 128, 79, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.dt.setFont(font)
        self.dt.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.dt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dt.setObjectName("dt")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(126, 128, 16, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_11.setObjectName("label_11")
        self.it = QtWidgets.QLabel(self.centralwidget)
        self.it.setGeometry(QtCore.QRect(64, 156, 79, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.it.setFont(font)
        self.it.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.it.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.it.setObjectName("it")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(126, 156, 16, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_10.setObjectName("label_10")
        self.p1 = QtWidgets.QLabel(self.centralwidget)
        self.p1.setGeometry(QtCore.QRect(658, 528, 111, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.p1.setFont(font)
        self.p1.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.p1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.p1.setObjectName("p1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(726, 534, 33, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_3.setObjectName("label_3")
        self.t1 = QtWidgets.QLabel(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(658, 570, 91, 39))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.t1.setFont(font)
        self.t1.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.t1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.t1.setObjectName("t1")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(724, 574, 16, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_5.setObjectName("label_5")
        self.g = QtWidgets.QLabel(self.centralwidget)
        self.g.setGeometry(QtCore.QRect(348, 530, 85, 41))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.g.setFont(font)
        self.g.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.g.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.g.setObjectName("g")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 536, 21, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_4.setObjectName("label_4")
        self.zf = QtWidgets.QLabel(self.centralwidget)
        self.zf.setGeometry(QtCore.QRect(113, 532, 85, 35))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.zf.setFont(font)
        self.zf.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.zf.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.zf.setObjectName("zf")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(179, 536, 16, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_17.setObjectName("label_17")
        self.t2 = QtWidgets.QLabel(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(328, 777, 85, 39))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.t2.setFont(font)
        self.t2.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.t2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.t2.setObjectName("t2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(394, 782, 16, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_6.setObjectName("label_6")
        self.livelog_freeze_button = QtWidgets.QPushButton(self.centralwidget)
        self.livelog_freeze_button.setGeometry(QtCore.QRect(980, 927, 0, 19))
        self.livelog_freeze_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.livelog_freeze_button.setFont(font)
        self.livelog_freeze_button.setStyleSheet("QPushButton{\n"
"    color: rgba(69, 137, 178, .5);\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(69, 137, 178, 25);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgba(255,255,255,.2);\n"
"}\n"
"\n"
"QPushButton::checked{\n"
"    border: 1px solid rgba(0, 206, 53, .5);\n"
"    background-color: rgba(0,0,0,.3);\n"
"    color:white;\n"
"}")
        self.livelog_freeze_button.setCheckable(True)
        self.livelog_freeze_button.setDefault(False)
        self.livelog_freeze_button.setFlat(False)
        self.livelog_freeze_button.setObjectName("livelog_freeze_button")
        self.livelog_clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.livelog_clear_button.setGeometry(QtCore.QRect(980, 927, 0, 19))
        self.livelog_clear_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("GOST Common")
        font.setPointSize(8)
        self.livelog_clear_button.setFont(font)
        self.livelog_clear_button.setStyleSheet("QPushButton{\n"
"    color: rgba(69, 137, 178, .5);\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(69, 137, 178, 25);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgba(255,255,255,.2);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 1px solid rgba(0, 206, 53, .5);\n"
"    background-color: rgba(0,0,0,.3);\n"
"    color:white;\n"
"}")
        self.livelog_clear_button.setCheckable(False)
        self.livelog_clear_button.setDefault(False)
        self.livelog_clear_button.setFlat(False)
        self.livelog_clear_button.setObjectName("livelog_clear_button")
        self.caution_alarm = QtWidgets.QPushButton(self.centralwidget)
        self.caution_alarm.setGeometry(QtCore.QRect(1062, 10, 83, 43))
        self.caution_alarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(20)
        self.caution_alarm.setFont(font)
        self.caution_alarm.setStyleSheet("color: gray;\n"
"background-color:transparent;\n"
"border: 1px solid gray;")
        self.caution_alarm.setCheckable(False)
        self.caution_alarm.setObjectName("caution_alarm")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(664, 186, 23, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_13.setObjectName("label_13")
        self.m0 = QtWidgets.QLabel(self.centralwidget)
        self.m0.setGeometry(QtCore.QRect(600, 181, 87, 39))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.m0.setFont(font)
        self.m0.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.m0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.m0.setObjectName("m0")
        self.warning_alarm = QtWidgets.QPushButton(self.centralwidget)
        self.warning_alarm.setGeometry(QtCore.QRect(980, 10, 83, 43))
        self.warning_alarm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(14)
        self.warning_alarm.setFont(font)
        self.warning_alarm.setStyleSheet("color: gray;\n"
"background-color:B06309;\n"
"border: 1px solid gray;")
        self.warning_alarm.setCheckable(False)
        self.warning_alarm.setObjectName("warning_alarm")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(750, 186, 29, 29))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:#2d3438; \n"
"background-color:transparent;")
        self.label_14.setObjectName("label_14")
        self.dm0 = QtWidgets.QLabel(self.centralwidget)
        self.dm0.setGeometry(QtCore.QRect(686, 181, 95, 39))
        font = QtGui.QFont()
        font.setFamily("HUN-din 1451")
        font.setPointSize(12)
        self.dm0.setFont(font)
        self.dm0.setStyleSheet("color:#2d3438; \n"
"background-color:white;\n"
"padding: 2px;")
        self.dm0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dm0.setObjectName("dm0")
        self.dm0.raise_()
        self.m0.raise_()
        self.plotDropFrame.raise_()
        self.N2O_P0.raise_()
        self.flames.raise_()
        self.i2.raise_()
        self.Rnumbar.raise_()
        self.f1.raise_()
        self.f2.raise_()
        self.count.raise_()
        self.label_18.raise_()
        self.count_set.raise_()
        self.count_set_button.raise_()
        self.CSYNC.raise_()
        self.cmdbg.raise_()
        self.procbg.raise_()
        self.label.raise_()
        self._mtr_.raise_()
        self.p1probe_p1.raise_()
        self.t1probe_t1.raise_()
        self.gprobe_g.raise_()
        self.t2probe_t2.raise_()
        self.Rbool.raise_()
        self.Rnum.raise_()
        self.u2.raise_()
        self.R_u1.raise_()
        self.u2_I.raise_()
        self.B.raise_()
        self.B_u1.raise_()
        self.u1.raise_()
        self.A.raise_()
        self.u1_A.raise_()
        self.A_u1.raise_()
        self.u1_B.raise_()
        self.hdcsunderscore.raise_()
        self.adcs.raise_()
        self.adcs_u2.raise_()
        self.adcs_u1.raise_()
        self.fa1.raise_()
        self.fa2.raise_()
        self.dcs.raise_()
        self.N2O.raise_()
        self.label_12.raise_()
        self.N2O_T0.raise_()
        self.I.raise_()
        self.I_u2.raise_()
        self.I_v2.raise_()
        self.B_v1.raise_()
        self.A_v1.raise_()
        self.v2.raise_()
        self.label_19.raise_()
        self.v1.raise_()
        self.label_20.raise_()
        self.i1.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.u3disconn.raise_()
        self.u4disconn.raise_()
        self.pwrdisconn.raise_()
        self.v2_I.raise_()
        self.u2_2.raise_()
        self.u2_f1.raise_()
        self.f1_u2.raise_()
        self.v1_A.raise_()
        self.I_electrode.raise_()
        self.v1_B.raise_()
        self.v2_f1.raise_()
        self.f1_v2.raise_()
        self.count_set_button_expand.raise_()
        self.u2_adcs.raise_()
        self.u1_adcs.raise_()
        self.electrode_I.raise_()
        self.u1_R.raise_()
        self.proc_grad_bot.raise_()
        self.xyfbg.raise_()
        self.it_adcs.raise_()
        self.adcs_it.raise_()
        self.t1_t1probe.raise_()
        self.p1_p1probe.raise_()
        self.g_gprobe.raise_()
        self.t2_t2probe.raise_()
        self.motor_Rbool.raise_()
        self.Rbool_motor.raise_()
        self.R_B.raise_()
        self.B_R.raise_()
        self.B_A.raise_()
        self.A_B.raise_()
        self.A_n2o.raise_()
        self.n2o_A.raise_()
        self.livelog.raise_()
        self.livelog_expand.raise_()
        self.b2_toggle.raise_()
        self.b1_toggle.raise_()
        self.t0.raise_()
        self.label_8.raise_()
        self.p0.raise_()
        self.label_7.raise_()
        self.v0.raise_()
        self.label_9.raise_()
        self.dt.raise_()
        self.label_11.raise_()
        self.it.raise_()
        self.label_10.raise_()
        self.p1.raise_()
        self.label_3.raise_()
        self.t1.raise_()
        self.label_5.raise_()
        self.g.raise_()
        self.label_4.raise_()
        self.zf.raise_()
        self.label_17.raise_()
        self.t2.raise_()
        self.label_6.raise_()
        self.livelog_freeze_button.raise_()
        self.livelog_clear_button.raise_()
        self.caution_alarm.raise_()
        self.label_13.raise_()
        self.warning_alarm.raise_()
        self.label_14.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Digital Control Station - Human Control [HDCS] - Disconnected"))
        self.label_18.setText(_translate("MainWindow", "sec"))
        self.count.setText(_translate("MainWindow", "xxx.xx"))
        self.count_set_button.setText(_translate("MainWindow", ">"))
        self.CSYNC.setText(_translate("MainWindow", "!"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.f1_button.setText(_translate("MainWindow", "1"))
        self.f2_button.setText(_translate("MainWindow", "2"))
        self.fire_button.setText(_translate("MainWindow", "FIRE"))
        self.arm_button.setText(_translate("MainWindow", "ARM"))
        self.count_button.setText(_translate("MainWindow", "COUNT"))
        self.testdef_button.setText(_translate("MainWindow", "define test"))
        self.log_button.setText(_translate("MainWindow", "log"))
        self.newplot_button.setText(_translate("MainWindow", "create new plot"))
        self.plotfreeze_button.setText(_translate("MainWindow", "freeze plots"))
        self.stopplots_button.setText(_translate("MainWindow", "close all plots"))
        self.upload_button.setText(_translate("MainWindow", "upload to micros"))
        self.reconnect_button.setText(_translate("MainWindow", "connect to adcs"))
        self.reset_button.setText(_translate("MainWindow", "reset device"))
        self.f2.setText(_translate("MainWindow", "f2 active"))
        self.f1.setText(_translate("MainWindow", "f1 active"))
        self.proc_next_button.setText(_translate("MainWindow", "next"))
        self.label_2.setText(_translate("MainWindow", "procedure"))
        self.label.setText(_translate("MainWindow", "HDCS"))
        self.p1probe_p1.setText(_translate("MainWindow", "l"))
        self.t1probe_t1.setText(_translate("MainWindow", "l"))
        self.gprobe_g.setText(_translate("MainWindow", "l"))
        self.t2probe_t2.setText(_translate("MainWindow", "l"))
        self.Rbool.setText(_translate("MainWindow", "R"))
        self.Rnum.setText(_translate("MainWindow", "1.0"))
        self.R_u1.setText(_translate("MainWindow", "n"))
        self.u2.setText(_translate("MainWindow", "u2"))
        self.u2_I.setText(_translate("MainWindow", "n"))
        self.B.setText(_translate("MainWindow", "B"))
        self.B_u1.setText(_translate("MainWindow", "n"))
        self.u1.setText(_translate("MainWindow", "u1"))
        self.A.setText(_translate("MainWindow", "A"))
        self.u1_A.setText(_translate("MainWindow", "n"))
        self.A_u1.setText(_translate("MainWindow", "n"))
        self.u1_B.setText(_translate("MainWindow", "n"))
        self.adcs.setText(_translate("MainWindow", "ADCS"))
        self.adcs_u2.setText(_translate("MainWindow", "n"))
        self.adcs_u1.setText(_translate("MainWindow", "n"))
        self.fa1.setText(_translate("MainWindow", "⬆"))
        self.fa2.setText(_translate("MainWindow", "⬇"))
        self.dcs.setText(_translate("MainWindow", "⥯"))
        self.N2O.setText(_translate("MainWindow", "N O"))
        self.label_12.setText(_translate("MainWindow", "2"))
        self.I.setText(_translate("MainWindow", "I"))
        self.I_u2.setText(_translate("MainWindow", "n"))
        self.I_v2.setText(_translate("MainWindow", "n"))
        self.B_v1.setText(_translate("MainWindow", "n"))
        self.A_v1.setText(_translate("MainWindow", "n"))
        self.v2.setText(_translate("MainWindow", "xxx.xx"))
        self.label_19.setText(_translate("MainWindow", "v"))
        self.v1.setText(_translate("MainWindow", "xxx.xx"))
        self.label_20.setText(_translate("MainWindow", "v"))
        self.i1.setText(_translate("MainWindow", "xxx.xx"))
        self.label_21.setText(_translate("MainWindow", "a"))
        self.label_22.setText(_translate("MainWindow", "a"))
        self.i2.setText(_translate("MainWindow", "xxx.xx"))
        self.u3disconn.setText(_translate("MainWindow", "! U3 DISCONN"))
        self.u4disconn.setText(_translate("MainWindow", "! U4 DISCONN"))
        self.pwrdisconn.setText(_translate("MainWindow", "! PWR DISCONN"))
        self.v2_I.setText(_translate("MainWindow", "n"))
        self.u2_2.setText(_translate("MainWindow", "U2"))
        self.u2_f1.setText(_translate("MainWindow", "n"))
        self.f1_u2.setText(_translate("MainWindow", "n"))
        self.v1_A.setText(_translate("MainWindow", "n"))
        self.I_electrode.setText(_translate("MainWindow", "n"))
        self.v1_B.setText(_translate("MainWindow", "n"))
        self.v2_f1.setText(_translate("MainWindow", "n"))
        self.f1_v2.setText(_translate("MainWindow", "n"))
        self.count_set_button_expand.setText(_translate("MainWindow", "<"))
        self.u2_adcs.setText(_translate("MainWindow", "n"))
        self.u1_adcs.setText(_translate("MainWindow", "n"))
        self.electrode_I.setText(_translate("MainWindow", "n"))
        self.u1_R.setText(_translate("MainWindow", "n"))
        self.xf0.setText(_translate("MainWindow", "xxx.xx"))
        self.label_29.setText(_translate("MainWindow", "n"))
        self.yf0.setText(_translate("MainWindow", "xxx.xx"))
        self.label_25.setText(_translate("MainWindow", "n"))
        self.xf1.setText(_translate("MainWindow", "xxx.xx"))
        self.label_30.setText(_translate("MainWindow", "n"))
        self.yf1.setText(_translate("MainWindow", "xxx.xx"))
        self.label_33.setText(_translate("MainWindow", "n"))
        self.it_adcs.setText(_translate("MainWindow", "n"))
        self.adcs_it.setText(_translate("MainWindow", "n"))
        self.t1_t1probe.setText(_translate("MainWindow", "n"))
        self.p1_p1probe.setText(_translate("MainWindow", "n"))
        self.g_gprobe.setText(_translate("MainWindow", "n"))
        self.t2_t2probe.setText(_translate("MainWindow", "n"))
        self.motor_Rbool.setText(_translate("MainWindow", "n"))
        self.Rbool_motor.setText(_translate("MainWindow", "n"))
        self.R_B.setText(_translate("MainWindow", "n"))
        self.B_R.setText(_translate("MainWindow", "n"))
        self.B_A.setText(_translate("MainWindow", "n"))
        self.A_B.setText(_translate("MainWindow", "n"))
        self.A_n2o.setText(_translate("MainWindow", "n"))
        self.n2o_A.setText(_translate("MainWindow", "n"))
        self.livelog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'GOST Common\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.livelog_expand.setText(_translate("MainWindow", "<"))
        self.b2_toggle.setText(_translate("MainWindow", "bus 2"))
        self.b1_toggle.setText(_translate("MainWindow", "bus 1"))
        self.t0.setText(_translate("MainWindow", "xxx.xx"))
        self.label_8.setText(_translate("MainWindow", "C"))
        self.p0.setText(_translate("MainWindow", "xxx.xx"))
        self.label_7.setText(_translate("MainWindow", "mpa"))
        self.v0.setText(_translate("MainWindow", "xxx.xx"))
        self.label_9.setText(_translate("MainWindow", "v"))
        self.dt.setText(_translate("MainWindow", "xxx.xx"))
        self.label_11.setText(_translate("MainWindow", "s"))
        self.it.setText(_translate("MainWindow", "xxx.xx"))
        self.label_10.setText(_translate("MainWindow", "C"))
        self.p1.setText(_translate("MainWindow", "xxx.xx"))
        self.label_3.setText(_translate("MainWindow", "kpa"))
        self.t1.setText(_translate("MainWindow", "xxx.xx"))
        self.label_5.setText(_translate("MainWindow", "C"))
        self.g.setText(_translate("MainWindow", "xxx.xx"))
        self.label_4.setText(_translate("MainWindow", "g0"))
        self.zf.setText(_translate("MainWindow", "xxx.xx"))
        self.label_17.setText(_translate("MainWindow", "n"))
        self.t2.setText(_translate("MainWindow", "xxx.xx"))
        self.label_6.setText(_translate("MainWindow", "c"))
        self.livelog_freeze_button.setText(_translate("MainWindow", "freeze"))
        self.livelog_clear_button.setText(_translate("MainWindow", "clear"))
        self.caution_alarm.setText(_translate("MainWindow", "⨻"))
        self.label_13.setText(_translate("MainWindow", "g"))
        self.m0.setText(_translate("MainWindow", "xxx.xx"))
        self.warning_alarm.setText(_translate("MainWindow", "⚠"))
        self.label_14.setText(_translate("MainWindow", "g/s"))
        self.dm0.setText(_translate("MainWindow", "xxx.xx"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

